const channelList = [
  {
    rating: 5,
    title: "GYM A Entrenar!",
    description: "playlist por mes por semana por dia para entrenar",
    url: "/gym-app.html",
    info: "",
    logo: "./Gym-A-Entrenar.png",
    costo: "gratis",
    tipo: ["gratis"],
    isFavorite: false,
  },
  {
    rating: 5,
    title: "YouTube",
    description: "",
    url: "https://www.youtube.com",
    info: "",
    logo: "./youtube-1.png",
    costo: "gratis",
    tipo: ["gratis"],
    isFavorite: false,
  },
  {
    rating: 5,
    title: "Netflix",
    description: "Watch Netflix on your TV.",
    url: "https://www.netflix.com/",
    info: "https://www.youtube.com/c/TopCinema/search?query=netflix",
    logo: "./netflix.png",
    costo: "subscripcion",
    tipo: ["subscripcion"],
    isFavorite: false,
  },
  {
    rating: 5,
    title: "Prime Video",
    description: "",
    url: "https://www.primevideo.com/",
    info: "https://www.youtube.com/c/TopCinema/search?query=prime%20video",
    logo: "./prime-video.png",
    costo: "subscripcion",
    tipo: ["subscripcion"],
    isFavorite: false,
  },
  {
    rating: 5,
    title: "Max",
    description: "",
    url: "https://play.max.com/home",
    info: "https://www.youtube.com/c/TopCinema/search?query=hbo%20max",
    logo: "./max-hbo-460x0w.png",
    costo: "subscripcion",
    tipo: ["subscripcion"],
    isFavorite: false,
  },
  {
    rating: 5,
    title: "Disney+",
    description: "",
    url: "https://www.disneyplus.com/home",
    info: "https://www.youtube.com/c/TopCinema/search?query=disney",
    logo: "./disney-plus.png",
    costo: "subscripcion",
    tipo: ["subscripcion"],
    isFavorite: false,
  },
  {
    rating: 5,
    title: "Paramount+",
    description: "",
    url: "https://www.paramountplus.com/",
    info: "https://www.youtube.com/c/TopCinema/search?query=paramount%20plus",
    logo: "./paramount-plus.png",
    costo: "subscripcion",
    tipo: ["subscripcion"],
    isFavorite: false,
  },
  {
    rating: 5,
    title: "Crunchiroll",
    description: "",
    url: "https://www.crunchyroll.com/es/videos/popular",
    info: "https://www.youtube.com/playlist?list=PLm8koqOGgz6yAv7rXlfWpy1rtV_Y0LZgq",
    logo: "./crunchyroll.png",
    costo: "gratis o subscripcion",
    tipo: ["subscripcion", "animacion"],
    isFavorite: false,
  },
  {
    rating: 4,
    title: "Spotify",
    description: "",
    url: "https://open.spotify.com/collection/albums",
    info: "",
    logo: "./spotify.png",
    costo: "gratis o subscripcion",
    tipo: ["subscripcion", "musica"],
    isFavorite: false,
  },
  {
    rating: 5,
    title: "canal 8 MDP",
    description: "",
    url: "/canal-08-mdq.html",
    info: "https://canal8mardelplata.com.ar/programacion/",
    logo: "./canal8-mdq-2022.png",
    costo: "gratis",
    tipo: ["in-spanish", "argentino", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 5,
    title: "Canal 10 MDP",
    description: "",
    url: "/canal10-mdq.html",
    info: "https://www.canal10mardelplata.tv/DiasyHorarios/",
    logo: "./canal-10-mdq-2.jpg",
    costo: "gratis",
    tipo: ["in-spanish", "argentino", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 5,
    title: "Pluto TV",
    description: "",
    url: "https://pluto.tv/on-demand",
    info: "https://www.youtube.com/c/PlutoTVLatam",
    logo: "./pluto-tv.png",
    costo: "gratis",
    tipo: ["gratis", "in-spanish"],
    isFavorite: false,
  },
  {
    rating: 2,
    title: "Play MercadoLibre",
    description: "",
    url: "http://play.mercadolibre.com.ar/",
    info: "https://www.instagram.com/appletv",
    logo: "./mercadolibre-play-logo-2.png",
    costo: "subscripcion",
    tipo: ["subscripcion"],
    isFavorite: false,
  },
  {
    rating: 2,
    title: "AppleTv+",
    description: "",
    url: "https://tv.apple.com/",
    info: "https://www.instagram.com/appletvplus/?hl=es",
    logo: "./apple-tv.png",
    costo: "subscripcion",
    tipo: ["subscripcion"],
    isFavorite: false,
  },
  {
    rating: 0,
    title: "Teatro Tv (Teatrix)",
    description: "",
    url: "https://teatrix.com/",
    info: "https://teatrix.com/noticias",
    logo: "./teatrix-tv-vivo.png",
    costo: "gratis",
    tipo: ["gratis", "in-spanish", "argentino"],
    isFavorite: false,
  },
  {
    rating: 4,
    title: "Mi TE-LE-FE",
    description: "",
    url: "https://mitelefe.com/vivo/",
    info: "",
    logo: "./mi-telefe.png",
    costo: "gratis",
    tipo: ["in-spanish", "argentino", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 4,
    title: "Canal 9 BsAs",
    description: "",
    url: "https://tvlibre.cc/en-vivo/el-nueve/",
    info: "",
    logo: "./elnueve-bsas-ar.png",
    costo: "gratis",
    tipo: ["in-spanish", "argentino", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 4,
    title: "America TV",
    description: "",
    url: "https://tvlibre.cc/en-vivo/america-tv/",
    info: "",
    logo: "./america-tv.png",
    costo: "gratis",
    tipo: ["in-spanish", "argentino", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 5,
    title: "Twitch",
    description: "",
    url: "https://www.twitch.tv/directory/following/live",
    info: "",
    logo: "./Twitch.png",
    costo: "gratis",
    tipo: ["gratis"],
    isFavorite: false,
  },
  // {
  //   rating: 4,
  //   title: "Cont.ar",
  //   description: "",
  //   url: "https://www.cont.ar/",
  //   info: "",
  //   logo: "./cont.ar.png",
  //   costo: "gratis",
  //   tipo: ["gratis", "in-spanish", "argentino"],
  //   isFavorite: false,
  // },
  // {
  //   rating: 4,
  //   title: "Cont.ar VIVO",
  //   description: "",
  //   url: "https://www.cont.ar/live",
  //   info: "",
  //   logo: "./cont.ar.png",
  //   costo: "gratis",
  //   tipo: ["in-spanish", "argentino", "tv-en-vivo"],
  //   isFavorite: false,
  // },
  {
    rating: 4,
    title: "Paka Paka",
    description: "",
    url: "https://tvlibre.cc/eventos/sin-chat/?r=L2h0bWwvZmwvP2dldD1VRUZMUVY5UVFVdEI=",
    info: "",
    logo: "./paka-paka.jpeg",
    costo: "gratis",
    tipo: ["in-spanish", "argentino", "animacion"],
    isFavorite: false,
  },
  {
    rating: 4,
    title: "CineAR Play",
    description: "",
    url: "https://play.cine.ar/inicio",
    info: "",
    logo: "./cinear-play-1.png",
    costo: "gratis",
    tipo: ["gratis", "in-spanish", "argentino"],
    isFavorite: false,
  },
  {
    rating: 5,
    title: "Vix",
    description: "",
    url: "https://www.vix.com/es-es/ondemand",
    info: "",
    logo: "./vix-tv.jpg",
    costo: "gratis",
    tipo: ["gratis", "in-spanish", "mexico"],
    isFavorite: false,
  },
  {
    rating: 5,
    title: "WeTv",
    description: "",
    url: "https://wetv.vip/es",
    info: "",
    logo: "./wetv.jpg",
    costo: "gratis",
    tipo: ["gratis", "china"],
    isFavorite: false,
  },
  {
    rating: 5,
    title: "Playz",
    description: "",
    url: "https://www.rtve.es/playz/",
    info: "",
    logo: "./playz.png",
    costo: "gratis",
    tipo: ["gratis", "in-spanish", "españa"],
    isFavorite: false,
  },
  {
    rating: 5,
    title: "Canela TV",
    description: "",
    url: "https://www.canela.tv/",
    info: "",
    logo: "./canela-tv.png",
    costo: "gratis",
    tipo: ["gratis", "in-spanish"],
    isFavorite: false,
  },
  {
    rating: 5,
    title: "Octubre TV",
    description: "",
    url: "https://octubretv.com/",
    info: "",
    logo: "./OctubreTv.png",
    costo: "gratis",
    tipo: ["gratis", "in-spanish"],
    isFavorite: false,
  },
  {
    rating: 5,
    title: "Star+",
    description: "",
    url: "https://tvlibre.cc/en-vivo/star-channel/",
    info: "https://www.youtube.com/c/TopCinema/search?query=Star",
    logo: "./star-plus.png",
    costo: "subscripcion",
    tipo: ["subscripcion"],
    isFavorite: false,
  },
  // {
  //   rating: 5,
  //   title: "Cuevana (3)",
  //   description: "",
  //   url: "https://ww1.cuevana3.me/",
  //   info: "",
  //   logo: "./cuevana-3.png",
  //   costo: "gratis",
  //   tipo: ["gratis"],
  //   isFavorite: false,
  // },
  {
    rating: 5,
    title: "pelisplus (estrenos)",
    description: "",
    url: "https://pelisplusvip.com",
    info: "",
    logo: "./pelisplus-1.png",
    costo: "gratis",
    tipo: ["gratis"],
    isFavorite: false,
  },
  {
    rating: 5,
    title: "PELISFLIX",
    description: "",
    url: "https://pelisflix1.lol/",
    info: "",
    logo: "./pelis-flix-2.png",
    costo: "gratis",
    tipo: ["gratis"],
    isFavorite: false,
  },
  // {
  //   rating: 5,
  //   title: "PELISFLIX 2",
  //   description: "",
  //   url: "https://pelisflix.trade/",
  //   info: "",
  //   logo: "./pelisflix-icon-2.jpg",
  //   costo: "gratis",
  //   tipo: ["gratis"],
  //   isFavorite: false,
  // },
  {
    rating: 5,
    title: "GNULA - Series",
    description: "",
    url: "https://gnulaseries.nu/",
    info: "",
    logo: "./gnula-serie.png",
    costo: "gratis",
    tipo: ["gratis"],
    isFavorite: false,
  },
  // {
  //   rating: 5,
  //   title: "GNULA - Peliculas",
  //   description: "",
  //   url: "https://gnula.nu/",
  //   info: "",
  //   logo: "./gnula-pelis.jpg",
  //   costo: "gratis",
  //   tipo: ["gratis"],
  //   isFavorite: false,
  // },
  // {
  //   rating: 0,
  //   title: "Otakuverso",
  //   description: "",
  //   url: "https://otakuverso.net/animes",
  //   info: "",
  //   logo: "./otakuverso.png",
  //   costo: "gratis",
  //   tipo: ["animacion", "in-spanish"],
  //   isFavorite: false,
  // },
  {
    rating: 0,
    title: "Anime Blix",
    description: "",
    url: "https://vwv.animeblix.org/animes",
    info: "",
    logo: "./animeblix-2.png",
    costo: "gratis",
    tipo: ["animacion"],
    isFavorite: false,
  },
  {
    rating: 0,
    title: "Anime FLV",
    description: "",
    url: "https://www3.animeflv.net/browse",
    info: "https://somoskudasai.com/categoria/noticias/anime/",
    logo: "./anime-flv-1.png",
    costo: "gratis",
    tipo: ["animacion"],
    isFavorite: false,
  },
  // {
  //   rating: 0,
  //   title: "Otakustv",
  //   description: "",
  //   url: "https://www1.otakustv.com/animes",
  //   info: "",
  //   logo: "./otakus-tv.png",
  //   costo: "gratis",
  //   tipo: ["animacion"],
  //   isFavorite: false,
  // },
  {
    rating: 0,
    title: "MonosChinos",
    description: "",
    url: "https://ww1.monoschinos3.com/animes",
    info: "https://ww1.monoschinos3.com/calendario",
    logo: "./monoschinos.png",
    costo: "gratis",
    tipo: ["animacion"],
    isFavorite: false,
  }, 
  {
    rating: 0,
    title: "Veranime",
    description: "",
    url: "https://wwv.veranimes.net/",
    info: "",
    logo: "./ver-anime_org.png",
    costo: "gratis",
    tipo: ["animacion"],
    isFavorite: false,
  },
  {
    rating: 0,
    title: "Anime Onegai",
    description: "",
    url: "https://www.animeonegai.com/es/page/home",
    info: "https://noticias.animeonegai.com/",
    logo: "./anime-onegai.png",
    costo: "gratis",
    tipo: ["animacion"],
    isFavorite: false,
  },
  {
    rating: 0,
    title: "LA. Cartoons",
    description: "",
    url: "https://www.lacartoons.com/",
    info: "",
    logo: "./kids-tv.jpg",
    costo: "gratis",
    tipo: ["animacion"],
    isFavorite: false,
  },
  // {
  //   rating: 0,
  //   title: "Kids Peliculas",
  //   description: "",
  //   url: "https://www.gnula2.co/categoria/animacion/",
  //   info: "",
  //   logo: "./kids-tv-peliculas.jpg",
  //   costo: "gratis",
  //   tipo: ["animacion"],
  //   isFavorite: false,
  // },
  {
    rating: 0,
    title: "Disney Channel",
    description: "",
    url: "https://tvlibre.cc/en-vivo/disney-channel/",
    info: "",
    logo: "./Disney-channel.png",
    costo: "gratis",
    tipo: ["animacion", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 0,
    title: "Cartoon Network (vivo)",
    description: "",
    url: "https://tvlibre.cc/en-vivo/cartoon-network/",
    info: "",
    logo: "./cartoon-network.png",
    costo: "gratis",
    tipo: ["animacion", "tv-en-vivo"],
    isFavorite: false,
  },
  // {
  //   rating: 0,
  //   title: "Boing (vivo)",
  //   description: "",
  //   url: "https://www.telegratishd.com/boing-en-vivo.html",
  //   info: "",
  //   logo: "./boing-tv.png",
  //   costo: "gratis",
  //   tipo: ["animacion", "tv-en-vivo"],
  //   isFavorite: false,
  // },
  {
    rating: 0,
    title: "nikelodeon (vivo)",
    description: "",
    url: "https://tvlibre.cc/en-vivo/nick/",
    info: "",
    logo: "./nikelodeon.png",
    costo: "gratis",
    tipo: ["animacion", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 0,
    title: "ver-television",
    description: "",
    url: "https://tvlibre.cc/",
    info: "",
    logo: "./tv-libre.png",
    costo: "gratis",
    tipo: ["gratis"],
    isFavorite: false,
  },
  // {
  //   rating: 0,
  //   title: "photocall.tv",
  //   description: "",
  //   url: "https://photocalltv.site/",
  //   info: "",
  //   logo: "./tv-ipod-icon.jpg",
  //   costo: "gratis",
  //   tipo: ["gratis"],
  //   isFavorite: false,
  // },
  // {
  //   rating: 0,
  //   title: "TV ARG HD",
  //   description: "",
  //   url: "https://www.tvarghd.com/",
  //   info: "",
  //   logo: "./argentina-tv-hd.png",
  //   costo: "gratis",
  //   tipo: ["in-spanish", "argentino", "youtube"],
  //   isFavorite: false,
  // },
  {
    rating: 4,
    title: "YouTube Music",
    description: "",
    url: "https://music.youtube.com/",
    info: "",
    logo: "./youtube-music.png",
    costo: "gratis o subscripcion",
    tipo: ["subscripcion", "musica"],
    isFavorite: false,
  },
  {
    rating: 4,
    title: "Amazon Music",
    description: "",
    url: "https://music.amazon.com/my/library",
    info: "",
    logo: "./amazon-music-460x0w.png",
    costo: "subscripcion",
    tipo: ["subscripcion", "musica"],
    isFavorite: false,
  },

  {
    rating: 0,
    title: "Conciertos Clasicos",
    description: "",
    url: "https://www.youtube.com/watch?v=ZqaJWiExZqk&list=PLGiHySZ9dpHhqQbOtN9eAL4MxRonA6KHa&index=2&ab_channel=FranceMusiqueconcerts",
    info: "",
    logo: "./conciertos-clasicos.png",
    costo: "gratis",
    tipo: ["musica", "youtube"],
    isFavorite: false,
  },
  {
    rating: 0,
    title: "Recitales",
    description: "",
    url: "https://www.youtube.com/watch?v=KhCNz8pw3tg&list=PL54835teYYB6TXx0j37rArlHeS2Nzi9Fw&index=6",
    info: "",
    logo: "./rock.jpg",
    costo: "gratis",
    tipo: ["musica"],
    isFavorite: false,
  },
  {
    rating: 0,
    title: "80's Hits",
    description: "",
    url: "https://music.youtube.com/watch?v=uPudE8nDog0&list=PLGiHySZ9dpHjlDEYC2BMU0ELsjqxa14UJ",
    info: "",
    logo: "./music-80s.jpeg",
    costo: "gratis",
    tipo: ["musica", "youtube"],
    isFavorite: false,
  },
  {
    rating: 0,
    title: "90's Hits",
    description: "",
    url: "https://music.youtube.com/watch?v=xwtdhWltSIg&list=PLGiHySZ9dpHid6vmmeVPUH-HKWjFCaxzs",
    info: "",
    logo: "./music-90s.jpg",
    costo: "gratis",
    tipo: ["musica", "youtube"],
    isFavorite: false,
  },
  {
    rating: 0,
    title: "2000's Hits",
    description: "",
    url: "https://www.youtube.com/watch?v=5NPBIwQyPWE&list=PLs_BtJUr-PzTyUumIEXrwD9z6vhozIPKJ&index=48&ab_channel=AvrilLavigneVEVO",
    info: "",
    logo: "./music-2000s.jpg",
    costo: "gratis",
    tipo: ["musica", "youtube"],
    isFavorite: false,
  },
  {
    rating: 0,
    title: "Radios MDP",
    description: "",
    url: "https://radioarg.net/buenos-aires/mar-del-plata",
    info: "",
    logo: "./RadiosArg.Net.png",
    costo: "gratis",
    tipo: ["argentino", "musica"],
    isFavorite: false,
  },
  {
    rating: 0,
    title: "Radios Argentina",
    description: "",
    url: "https://radioarg.com/",
    info: "",
    logo: "./radios-argentina.png",
    costo: "gratis",
    tipo: ["argentino", "musica"],
    isFavorite: false,
  },
  {
    rating: 1,
    title: "Depor TV",
    description: "",
    url: "https://tvlibre.cc/en-vivo/deportv/",
    info: "",
    logo: "./deportv.jpg",
    costo: "gratis",
    tipo: ["in-spanish", "argentino", "deporte", "youtube"],
    isFavorite: false,
  },
  {
    rating: 1,
    title: "Red Bull TV",
    description: "",
    url: "https://www.redbull.com/ar-es/discover",
    info: "",
    logo: "./redbull-tv.png",
    costo: "gratis",
    tipo: ["gratis", "deporte"],
    isFavorite: false,
  },
  {
    rating: 1,
    title: "FMS TV",
    description: "",
    url: "https://www.youtube.com/@Urbanroosters/videos",
    info: "",
    logo: "./FMS-24hs.jpg",
    costo: "gratis",
    tipo: ["in-spanish", "gratis", "deporte", "youtube"],
    isFavorite: false,
  },
  {
    rating: 1,
    title: "Plex Tv (en ingles)",
    description: "",
    url: "https://watch.plex.tv/movies-and-shows",
    info: "",
    logo: "./Plex.webp",
    costo: "gratis",
    tipo: ["gratis", "in-english"],
    isFavorite: false,
  },
  {
    rating: 1,
    title: "Ororo.TV",
    description: "",
    url: "https://ororo.tv/es/shows/",
    info: "",
    logo: "./ororo-tv.jpg",
    costo: "gratis",
    tipo: ["gratis"],
    isFavorite: false,
  },
  {
    rating: 0,
    title: "MUBI",
    description: "Gran Cine en Streaming",
    url: "https://mubi.com/es/films?sort=popularity_quality_score",
    info: "",
    logo: "./mubi-460x0w.png",
    costo: "subscripcion",
    tipo: ["subscripcion"],
    isFavorite: false,
  },
  {
    rating: 0,
    title: "DirecTV GO",
    description: "",
    url: "https://www.directvgo.com/home/watch",
    info: "",
    logo: "./directv-go.png",
    costo: "subscripcion",
    tipo: ["subscripcion", "in-spanish", "argentino"],
    isFavorite: false,
  },
  {
    rating: 0,
    title: "Teatrix",
    description: "",
    url: "https://teatrix.com/",
    info: "teatro como en el teatro",
    logo: "./teatrix.png",
    costo: "subscripcion",
    tipo: ["subscripcion", "in-spanish", "argentino"],
    isFavorite: false,
  },
  {
    rating: 0,
    title: "Udemy",
    description: "",
    url: "https://www.udemy.com/",
    info: "Ahorra y aprende a lo grande",
    logo: "./Udemy.webp",
    costo: "subscripcion",
    tipo: ["subscripcion"],
    isFavorite: false,
  },

  {
    rating: 5,
    title: "TV Publica",
    description: "",
    url: "https://www.youtube.com/user/TVPublicaArgentina",
    info: "",
    logo: "./TV-Publica.png",
    costo: "gratis",
    tipo: ["in-spanish", "argentino", "youtube"],
    isFavorite: false,
  },
  {
    rating: 5,
    title: "Canal Encuentro",
    description: "",
    url: "https://tvlibre.cc/en-vivo/encuentro/",
    info: "",
    logo: "./canal-encuentro.png",
    costo: "gratis",
    tipo: ["in-spanish", "argentino", "youtube"],
    isFavorite: false,
  },
  {
    rating: 0,
    title: "DW - Documental",
    description: "",
    url: "https://www.youtube.com/c/DWDocumental/videos",
    info: "",
    logo: "./dw-documentales.jpg",
    costo: "gratis",
    tipo: ["in-spanish", "youtube"],
    isFavorite: false,
  },
  {
    rating: 3,
    title: "Cronica TV",
    description: "",
    url: "https://tvlibre.cc/en-vivo/cronica/",
    info: "",
    logo: "./cronica-tv.png",
    costo: "gratis",
    tipo: ["in-spanish", "argentino", "youtube", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 2,
    title: "TN en vivo",
    description: "",
    url: "https://tvlibre.cc/en-vivo/tn/",
    info: "",
    logo: "./TN-vivo.png",
    costo: "gratis",
    tipo: ["in-spanish", "argentino", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 2,
    title: "C5N",
    description: "",
    url: "https://www.youtube.com/@c5n/streams",
    info: "",
    logo: "./c5n.png",
    costo: "gratis",
    tipo: ["in-spanish", "argentino", "youtube", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 2,
    title: "La Nacion+",
    description: "",
    url: "https://tvlibre.cc/en-vivo/ln/",
    info: "",
    logo: "./la-nacion.png",
    costo: "gratis",
    tipo: ["in-spanish", "argentino", "youtube", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 2,
    title: "Canal 26",
    description: "",
    url: "https://tvlibre.cc/en-vivo/canal-26/",
    info: "",
    logo: "./canal-26.jpg",
    costo: "gratis",
    tipo: ["in-spanish", "argentino", "youtube", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 2,
    title: "Canal 4 ( Uruguay )",
    description: "",
    url: "https://tvlibre.cc/en-vivo/canal4uy/",
    info: "",
    logo: "./canal-26.jpg",
    costo: "gratis",
    tipo: ["in-spanish", "argentino", "youtube", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 2,
    title: "TYC Sport",
    description: "",
    url: "https://tvlibre.cc/en-vivo/tyc-sports/",
    info: "",
    logo: "./TyC_Sports.webp",
    costo: "gratis",
    tipo: ["in-spanish", "deporte", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 2,
    title: "ESPN 1",
    description: "",
    url: "https://tvlibre.cc/en-vivo/espn/",
    info: "",
    logo: "./espn.png",
    costo: "gratis",
    tipo: ["in-spanish", "deporte", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 2,
    title: "Fox Sports",
    description: "",
    url: "https://tvlibre.cc/en-vivo/fox-sports/",
    info: "",
    logo: "./fox-sports.png",
    costo: "gratis",
    tipo: ["in-spanish", "deporte", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 2,
    title: "DirecTV Sports",
    description: "",
    url: "https://tvlibre.cc/en-vivo/dsports/",
    info: "",
    logo: "./directv-sport.png",
    costo: "gratis",
    tipo: ["in-spanish", "deporte", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 2,
    title: "Futbol Libre TV",
    description: "",
    url: "https://librepelota.pe/",
    info: "",
    logo: "./futbol-libre-tv.jpg",
    costo: "gratis",
    tipo: ["in-spanish", "deporte", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 2,
    title: "Libre Futbol",
    description: "",
    url: "https://pelota-libres.su/",
    info: "",
    logo: "./futbol-libre-1.png",
    costo: "gratis",
    tipo: ["in-spanish", "deporte", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 2,
    title: "Futbol libre 3",
    description: "",
    url: "https://pelota-libre.net/",
    info: "",
    logo: "./free-football-tv.jpg",
    costo: "gratis",
    tipo: ["in-spanish", "deporte", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 2,
    title: "AXN (vivo)",
    description: "",
    url: "https://tvlibre.cc/en-vivo/axn/",
    info: "",
    logo: "./axn-tv.png",
    costo: "gratis",
    tipo: ["in-spanish", "gratis", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 2,
    title: "Warner TV",
    description: "",
    url: "https://tvlibre.cc/en-vivo/warner/",
    info: "",
    logo: "./warner-channel.png",
    costo: "gratis",
    tipo: ["in-spanish", "gratis", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 2,
    title: "Universal Premier",
    description: "",
    url: "https://tvlibre.cc/en-vivo/universal-premiere/",
    info: "",
    logo: "./universal-tv.png",
    costo: "gratis",
    tipo: ["in-spanish", "gratis", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 2,
    title: "Universal Cinema",
    description: "",
    url: "https://tvlibre.cc/en-vivo/universal-cinema/",
    info: "",
    logo: "./universal-tv.png",
    costo: "gratis",
    tipo: ["in-spanish", "gratis", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 2,
    title: "Universal Comedy",
    description: "",
    url: "https://tvlibre.cc/en-vivo/universal-comedy/",
    info: "",
    logo: "./universal-tv.png",
    costo: "gratis",
    tipo: ["in-spanish", "gratis", "tv-en-vivo"],
    isFavorite: false,
  },

  {
    rating: 2,
    title: "TNT Canal",
    description: "",
    url: "https://tvlibre.cc/en-vivo/tnt/",
    info: "",
    logo: "./tnt-channel.png",
    costo: "gratis",
    tipo: ["in-spanish", "gratis", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 2,
    title: "TNT Series",
    description: "",
    url: "https://tvlibre.cc/en-vivo/tnt-series/",
    info: "",
    logo: "./tnt-channel.png",
    costo: "gratis",
    tipo: ["in-spanish", "gratis", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 2,
    title: "SPACE",
    description: "",
    url: "https://tvlibre.cc/en-vivo/space/",
    info: "",
    logo: "./space-channel.png",
    costo: "gratis",
    tipo: ["in-spanish", "gratis", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 2,
    title: "Cine Canal",
    description: "",
    url: "https://tvlibre.cc/en-vivo/cinecanal/",
    info: "",
    logo: "./cine-canal.png",
    costo: "gratis",
    tipo: ["in-spanish", "gratis", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 2,
    title: "Cine Max",
    description: "",
    url: "https://tvlibre.cc/en-vivo/cinemax/",
    info: "",
    logo: "./cinemax.png",
    costo: "gratis",
    tipo: ["in-spanish", "gratis", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 2,
    title: "Sony Channel",
    description: "",
    url: "https://tvlibre.cc/en-vivo/sony-channel/",
    info: "",
    logo: "./sony-channel.webp",
    costo: "gratis",
    tipo: ["in-spanish", "gratis", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 2,
    title: "HBO Channel",
    description: "",
    url: "https://tvlibre.cc/en-vivo/hbo/",
    info: "",
    logo: "./sony-channel.webp",
    costo: "gratis",
    tipo: ["in-spanish", "gratis", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 2,
    title: "HBO Family",
    description: "",
    url: "https://tvlibre.cc/en-vivo/hbo-family/",
    info: "",
    logo: "./sony-channel.webp",
    costo: "gratis",
    tipo: ["in-spanish", "gratis", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 2,
    title: "HBO Xtream",
    description: "",
    url: "https://tvlibre.cc/en-vivo/hbo-family/",
    info: "",
    logo: "./sony-channel.webp",
    costo: "gratis",
    tipo: ["in-spanish", "gratis", "tv-en-vivo"],
    isFavorite: false,
  },
  {
    rating: 2,
    title: "Syfy Channel",
    description: `Syfy es un canal temático internacional, dedicado mayoritariamente a la emisión de series y películas de ciencia ficción, si bien,
    también dedica espacios a los géneros de fantasía, horror y fenómenos paranormales.`,
    url: "https://tele-libre.org/en-vivo-online/syfy/",
    info: "",
    logo: "./syfy-channel-2.png",
    costo: "gratis",
    tipo: ["in-spanish", "gratis", "tv-en-vivo"],
    isFavorite: false,
  },
  // {
  //   rating: 0,
  //   title: "canal 8 MDP",
  //   description: "",
  //   url: "https://canal8mardelplata.com.ar/en-vivo-online/",
  //   info: "https://canal8mardelplata.com.ar/programacion/",
  //   logo: "./canal8-mdq-2022.png",
  //   costo: "gratis",
  //   tipo: ["in-spanish", "argentino"],
  //   isFavorite: false
  // },
  {
    rating: 0,
    title: "Whatsapp",
    description: "",
    // url: "whatsapp://send?text=YoYoYo",
    url: "https://web.whatsapp.com/",
    info: "",
    logo: "./whatsApp.png",
    costo: "gratis",
    tipo: ["app"],
    isFavorite: false,
  },
  {
    rating: 0,
    title: "Instagram",
    description: "",
    // url: "intent://instagram.com/#Intent;scheme=https;package=com.instagram.android;end",
    url: "https://instagram.com/",
    info: "",
    logo: "./instagram.webp",
    costo: "gratis",
    tipo: ["app"],
    isFavorite: false,
  },
  {
    rating: 0,
    title: "Tik-Tok",
    description: "",
    // url: "intent://instagram.com/#Intent;scheme=https;package=com.instagram.android;end",
    url: "https://www.tiktok.com/",
    info: "",
    logo: "./tik-tok.png",
    costo: "gratis",
    tipo: ["app"],
    isFavorite: false,
  },
  {
    rating: 0,
    title: "Facebook",
    description: "",
    // url: "intent://facebook.com/#Intent;scheme=https;package=com.facebook.android;end",
    url: "https://facebook.com/",
    info: "",
    logo: "./facebook.webp",
    costo: "gratis",
    tipo: ["app"],
    isFavorite: false,
  },
  {
    rating: 0,
    title: "X (twitter)",
    description: "",
    // url: "intent://twitter.com/#Intent;scheme=https;package=com.twitter.android;end",
    url: "https://twitter.com/",
    info: "",
    logo: "./twitter.jpg",
    costo: "gratis",
    tipo: ["app"],
    isFavorite: false,
  },
];
export default channelList;
